### ISSUE TITLE
Invalid code generated when constraints on enums are used

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#1282]
```smithy
$version: "2"

namespace hello

structure MyStruct {
    @length(max: 3)
    s: Str
}

enum Str {
    FOO
    BARS
}
```

This fails to compile on 0.18.2:

```
[error] /Users/kubukoz/projects/demos/target/scala-2.13/src_managed/main/scala/hello/MyStruct.scala:17:25: could not find implicit value for parameter constraint: smithy4s.RefinementProvider.Simple[smithy.api.Length,hello.Str]
[error]     Str.schema.validated(smithy.api.Length(min = None, max = Some(3L))).optional[MyStruct]("s", _.s),
[error]                         ^
[error] /Users/kubukoz/projects/demos/target/scala-2.13/src_managed/main/scala/hello/MyStruct.scala:19:14: missing argument list for method apply in object MyStruct
[error] Unapplied methods are only converted to functions when a function type is expected.
[error] You can make this conversion explicit by writing `apply _` or `apply(_)` instead of `apply`.
[error]     MyStruct.apply
[error]              ^
[error] two errors found
[error] (Compile / compileIncremental) Compilation failed
```

because there's no `RefinementProvider` available for enums, or a bijection that would allow deriving one.

BTW. `@length` / `@range` on the enum/intEnum shape itself are ignored by the codegen, including `val hints`.

Technically, the Smithy validators allow `@length` on enums, and `@range` on int enums. Should we support this somehow? I'm not sure there's a usecase in limiting the amount of allowed enum values further by imposing constraints, but I also can't say that nobody is doing so.

**Comment by Baccata** [comment]
As in people in your org are actually doing this ?

I suppose the rationale is that smithy considers enumerations as inherently open whilst we consider them inherently close.

Anyway, it may be possible to support it reasonably easily. I'll get back to you

**Comment by kubukoz** [comment]
As in "this is a free country, who knows what people are doing", not my org but perhaps another Smithy shop 😄

**Comment by Baccata** [comment]
How on earth did you bump into it then ? Do you just spend 2 hours randomising models every day for the kicks of it ?

**Comment by Baccata** [comment]
https://github.com/disneystreaming/smithy4s/pull/1283/files
